version: '3'
services:
    snippetbox:
        build:
          dockerfile: ./cmd/web/main.dockerfile
        ports:
            - "4000:4000"
        container_name: snippetbox
        restart: always
        deploy:
          mode: replicated
          replicas: 1

    mysql:
      image: mysql:latest
      container_name: mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=snippetbox
        - MYSQL_USER=snippetbox
        - MYSQL_PASSWORD=password
      volumes:
        - ./db-data/mysql/:/var/lib/mysql
      ports:
        - "3306:3306"
